#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/SQS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

#  Modify the given queue attributes.
#  For now, the only one is the visibility timeout.

if ARGV[0] == '-?' || ARGV.size != 3 then
	puts "usage: add-queue-permission queue account_id action"
	exit 1
end

name=ARGV[0]
account=ARGV[1]
action=ARGV[2]

Signal.trap("INT") { exit 2 }

config = BasicConfiguration.new
AwsContext.setup((ENV['AWS_CONTEXT'].to_sym rescue :aws))
sqs = AwsContext.instance.sqs(*config.keys)

begin
	url = (name.match(/^http/) ? name : sqs.get_queue_url(name))
	if url.nil? 
		puts "queue not found: #{name}"
	else
		if sqs.add_account_permission(url, account, action)
			puts "Action '#{action}' added for account '#{account}' on queue '#{name}'"
		else
			puts "Failed adding permission '#{action}' for account '#{account}' on queue '#{name}'"
		end
	end
rescue
	puts "error #{$!} #{name}"
	exit 1
end

