#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 1 then
   puts "usage: delete-as-group name"
   exit 1
end
name = ARGV[0]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
as = AwsContext.instance.as(*config.keys)
begin
  as.delete_auto_scaling_group(name)
  puts "deleted #{name}"
rescue
  puts "error #{$!}"
  exit 1
end
