#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV.size < 1
    usage = 'usage: as-delete-launch-config LaunchConfigurationName'
    about = 'Delete the specified launch configuration.'
    puts usage
    puts about
    exit 1
end

Signal.trap("INT") do
    exit 2
end

options = {}
options[:launch_configuration_name] = ARGV.shift

config = BasicConfiguration.new
as = AwsContext.instance.as(*config.keys)

begin
    as.delete_launch_configuration(options[:launch_configuration_name])
    puts "deleted #{options[:launch_configuration_name]}"
rescue
    puts "error: #{$!}"
    exit 1
end

exit 0
