#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV.size < 3
    usage = "usage: as-delete-trigger TriggerName --auto-scaling-group value"
    about = "Delete a trigger."
    puts usage
    puts about
    exit 1
end

Signal.trap("INT") do
    exit 2
end

options = {}
options[:trigger_name] = ARGV.shift

while ARGV.size > 0
    if ARGV[0] == '--auto-scaling-group'
        ARGV.shift
        options[:auto_scaling_group_name] = ARGV.shift
    end
end

config = BasicConfiguration.new
as = AwsContext.instance.as(*config.keys)

begin
    as.delete_trigger(options)
    puts "deleted trigger #{options[:trigger_name]} in group #{options[:auto_scaling_group_name]}"
rescue
    puts "error #{$!}"
    exit 1
end

exit 0
