#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 2 then
   puts "usage: set-desired-capacity group-name capacity"
   exit 1
end
options = {}
options[:auto_scaling_group_name]=ARGV[0]
options[:desired_capacity]=ARGV[1]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
as = AwsContext.instance.as(*config.keys)

begin
  result = as.create_desired_capacity(options)
  puts "set desired capacity for auto scaling group #{options[:auto_scaling_group_name]} to #{options[:desired_capacity]}"
rescue
  puts "error #{$!}"
  exit 1
end

exit 0
