#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/EC2'
require 'basic_configuration'
require 'aws_context'
require 'pp'

# Attach a volume to a running instance.

if ARGV[0] == '-?' || ARGV.size != 3 then
	puts "usage: attach-volume volume-id instance-id device"
	exit 1
end
volume_id = ARGV[0]
instance_id = ARGV[1]
device = ARGV[2]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)
begin
  res = ec2.attach_volume(volume_id, instance_id, device)
  puts "attached #{res[:status]}"
rescue
  puts "error #{$!} #{volume_id} #{instance_id} #{device}"
  exit 1
end

