#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 1 then
    puts "usage: create-access-key user-name"
    exit 1
end
options = {}
options[:user_name] = ARGV[0]

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    key = iam.create_access_key(options)
    puts "#{key.user_name} #{key.access_key_id} #{key.secret_access_key} #{key.status}"
rescue
    puts "error creating access key: #{$!}"
    exit 1
end

exit 0
