#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 1 then
    puts "usage: create-iam-user user-name [user-path]"
    exit 1
end
options = {}
options[:user_name] = ARGV[0]
options[:path] = ARGV[1] || '/'

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    user = iam.create_user(options)
    puts "#{user.user_name} #{user.user_id} #{user.arn}"
rescue
    puts "error creating aim user: #{$!}"
    exit 1
end

exit 0
