#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 1 then
    puts "usage: create-iam-group group-name [group-path]"
    exit 1
end
options = {}
options[:group_name] = ARGV[0]
options[:path] = ARGV[1] || '/'

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    group = iam.create_group(options)
    p group.group_id
rescue
    puts "error creating group: #{$!}"
    exit 1
end

exit 0
