#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/EC2'
require 'basic_configuration'
require 'aws_context'
require 'pp'

# Delete a snapshot.

if ARGV[0] == '-?' || ARGV.size != 1 then
	puts "usage: delete-snapshot snapshot-id"
	exit 1
end
snapshot_id = ARGV[0]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)
begin
  res = ec2.delete_snapshot(snapshot_id)
  puts "created #{res}"
rescue
  puts "error #{$!} #{snapshot_id}"
  exit 1
end

