#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 2 then
   puts "usage: delete-as-trigger as-group-name trigger-name"
   exit 1
end

options = {}
options[:auto_scaling_group_name] = ARGV[0]
options[:trigger_name] = ARGV[1]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
as = AwsContext.instance.as(*config.keys)

begin
  as.delete_trigger(options)
  puts "deleted trigger '#{options[:trigger_name]}' in group '#{options[:auto_scaling_group_name]}'"
rescue
  puts "error #{$!}"
  exit 1
end
