#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/ELB'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV.size < 1
    usage = "usage: elb-delete-lb LoadBalancerName"
    about = "Delete an existing LoadBalancer."
    puts usage
    puts about
    exit 1
end

Signal.trap("INT") do
    exit 2
end

options = {}
options[:load_balancer_name] = ARGV.shift

config = BasicConfiguration.new
elb = AwsContext.instance.elb(*config.keys)
begin
    elb.delete_load_balancer(options)
    puts "deleted #{options[:load_balancer_name]}"
rescue
    puts "error: #{$!}"
    exit 1
end

exit 0
