#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'basic_configuration'
require 'aws_context'
require 'pp'

usage = <<"eos"
SYNOPSIS
    elb-set-lb-listener-ssl-cert
      LoadBalancerName --lb-port value --cert-id value
eos

help = <<"eos"

DESCRIPTION
    Sets the SSL Certificate for the specified LoadBalancer port.
    Any previously set SSL Certificate is no longer used for this port.

ARGUMENTS
    LoadBalancerName
      Name of the LoadBalancer. You can also set this value using "--lb".
      Required.

    -c, --cert-id VALUE
      Id of SSL Certificate to use for the specified LoadBalancer port.
      Required.

    -l, --lb-port VALUE
      Port on LoadBalancer for which to set the SSL Certificate.
      Required.
eos

if ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV[0] == '-?'
  puts usage
  puts help
  exit 0
end

if ARGV.size < 5
  puts usage
  puts 'For more information and a full list of options, run "elb-set-lb-listener-ssl-cert --help"'
  exit 1
end

Signal.trap("INT") do
  exit 2
end

options = {}
unless ARGV[0] =~ Regexp.new('^-')
  options[:load_balancer_name] = ARGV.shift
end

while ARGV.size > 0
  if ARGV[0] == '--lb'
    unless options[:load_balancer_name].nil?
      puts "LoadBalancerName is already defined"
      puts usage
      exit 1
    end
    ARGV.shift
    options[:load_balancer_name] = ARGV.shift
  end
  if ARGV[0] == '--cert-id' || ARGV[0] == '-c'
    ARGV.shift
    options[:s_s_l_certificate_id] = ARGV.shift
  end
  if ARGV[0] == '--lb-port' || ARGV[0] == '-l'
    ARGV.shift
    options[:load_balancer_port] = ARGV.shift
  end
end

config = BasicConfiguration.new
elb = AwsContext.instance.elb(*config.keys)
  
begin
  result = elb.create_s_s_l_certificate(options)
  puts "certificate set"
rescue
  puts "error: #{$!}"
  exit 1
end

exit 0
