#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/AS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

usage = <<"eos"
SYNOPSIS
    elb-enable-zones-for-lb
      LoadBalancerName --availability-zones value[,value...]
eos

help = <<"eos"

DESCRIPTION
      Add availability zones to existing LoadBalancer

ARGUMENTS
    LoadBalancerName
      Name of the LoadBalancer. You can also set this value using "--lb".
      Required.

    -z, --availability-zones VALUE1,VALUE2,VALUE3...
      List of availability zones to add to the LoadBalancer.
      Required.
eos

if ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV[0] == '-?'
  puts usage
  puts help
  exit 0
end

if ARGV.size < 3
  puts usage
  puts 'For more information and a full list of options, run "elb-enable-zones-for-lb --help"'
  exit 1
end

Signal.trap("INT") do
    exit 2
end

options = {}
unless ARGV[0] =~ Regexp.new('^-')
  options[:load_balancer_name] = ARGV.shift
end

while ARGV.size > 0
  if ARGV[0] == '--lb'
    unless options[:load_balancer_name].nil?
      puts "LoadBalancerName is already defined"
      puts usage
      exit 1
    end
    ARGV.shift
    options[:load_balancer_name] = ARGV.shift
  end
  if ARGV[0] == '--availability-zones' || ARGV[0] == '-z'
    ARGV.shift
    options[:availability_zones] = ARGV.shift.split(',')
  end
end

config = BasicConfiguration.new
elb = AwsContext.instance.elb(*config.keys)

begin
  result = elb.create_availability_zone(options)
  puts "zones #{result.availability_zones.join(',')}"
rescue
  puts "error: #{$!}"
  exit 1
end

exit 0