#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'basic_configuration'
require 'aws_context'
require 'pp'

usage = <<"eos"
SYNOPSIS
    elb-delete-lb-listeners
      LoadBalancerName --lb-ports value[,value...]
eos

help = <<"eos"

DESCRIPTION
    Deletes a listener on an existing LoadBalancer

ARGUMENTS
    LoadBalancerName
      Name of the LoadBalancer. You can also set this value using "--lb".
      Required.

    -l, --lb-ports VALUE1,VALUE2,VALUE3...
      Port of the listener which to delete from the LoadBalancer.
      Required.
eos

if ARGV[0] == '--help' || ARGV[0] == '-h' || ARGV[0] == '-?'
  puts usage
  puts help
  exit 0
end

if ARGV.size < 3
  puts usage
  puts 'For more information and a full list of options, run "elb-delete-lb-listeners --help"'
  exit 1
end

Signal.trap("INT") do
  exit 2
end

options = {}
unless ARGV[0] =~ Regexp.new('^-')
  options[:load_balancer_name] = ARGV.shift
end

listeners = []
while ARGV.size > 0
  if ARGV[0] == '--lb'
    unless options[:load_balancer_name].nil?
      puts "LoadBalancerName is already defined"
      puts usage
      exit 1
    end
    ARGV.shift
    options[:load_balancer_name] = ARGV.shift
  end
  if ARGV[0] == '--lb-ports' || ARGV[0] == '-l'
    ARGV.shift
    options[:load_balancer_ports] = ARGV.shift.split(',')
  end
end

config = BasicConfiguration.new
elb = AwsContext.instance.elb(*config.keys)
  
begin
  result = elb.delete_listener(options)
  puts "listeners deleted"
rescue
  puts "error: #{$!}"
  exit 1
end

exit 0
