#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?'
  puts "usage: list-zones [region]"
  exit 1
end

region = ARGV[0]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)
begin
    zones = ec2.describe_availability_zones(region)
    zones.each do |z|
        puts "#{z[:name]} #{z[:state]}"
    end
rescue
    puts "error #{$!}"
    exit 1
end
