#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?'
    puts "usage: list-aim-users [path-prefix]"
    exit 1
end

filter = ARGV[0] || '/'

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    users = iam.describe_users({ :path_prefix => filter })
    users.each do |user|
        puts "#{user.user_name} #{user.user_id} #{user.arn}"
    end
rescue
    puts "error listing iam users: #{$!}"
    exit 1
end

exit 0