#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/EC2'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' 
  puts "usage: list-reserved_instances"
  exit 1
end

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)

begin
  instances = ec2.describe_reserved_instances
  instances.each do |i|
    duration = i[:duration].to_i / (60*60*24*30)
    puts "#{i[:zone]} #{i[:instance_type]} #{i[:count]} #{duration}months $#{i[:fixed_price]} $#{i[:usage_price]} #{i[:state]}"
  end
rescue
  puts "error #{$!}"
  exit 1
end
