#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 1 then
    puts "usage: list-access-keys user-name"
    exit 1
end
options = {}
options[:user_name] = ARGV[0]

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    keys = iam.describe_access_keys(options)
    keys.each do |key|
        puts "#{key.user_name} #{key.access_key_id} #{key.secret_access_key} #{key.status}"
    end
rescue
    puts "error getting access keys: #{$!}"
    exit 1
end

exit 0
