#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/EC2'
require 'basic_configuration'
require 'aws_context'
require 'pp'
	
# Add snapshot attributes
if ARGV[0] == '-?' || ARGV.size != 2 then
  puts "usage: make-snapshot-available snapshot-id account-id"
  exit 1
end
snapshot_id = ARGV[0]
account_id = ARGV[1]

Signal.trap("INT") do
    exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)
#begin
    res = ec2.modify_snapshot_attribute(snapshot_id, 'createVolumePermission', 'add', {'UserId' => account_id})
#rescue
#    puts "error #{$!} #{snapshot_id} #{account_id}"
#    exit 1
#end
