#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/EC2'
require 'basic_configuration'
require 'aws_context'
require 'pp'

# Release an ElasticIP address

if ARGV[0] == '-?' || ARGV.size != 1 then
  puts "usage: release-address public-ip"
  exit 1
end
public_ip = ARGV[0]

Signal.trap("INT") do
  exit 2
end

config = BasicConfiguration.new
ec2 = AwsContext.instance.ec2(*config.keys)
begin
  res = ec2.release_address(public_ip)
  #pp res
  puts res
rescue
  puts "error #{$!} #{public_ip}"
  exit 1
end

