#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/SQS'
require 'basic_configuration'
require 'aws_context'
require 'pp'

#  Modify the given queue attributes.
#  For now, the only one is the visibility timeout.

if ARGV[0] == '-?' || ARGV.size != 3 then
	puts "usage: set-queue-attribute queue key value"
	exit 1
end

name=ARGV[0]
key=ARGV[1]
value=ARGV[2]

Signal.trap("INT") { exit 2 }

config = BasicConfiguration.new
AwsContext.setup((ENV['AWS_CONTEXT'].to_sym rescue :aws))
sqs = AwsContext.instance.sqs(*config.keys)

begin
	url = (name.match(/^http/) ? name : sqs.list_queues(name).first)
	if url.nil? 
		puts "queue not found: #{name}"
	else  
		sqs.set_queue_attribute(url, value, key)
	end
rescue
	puts "error #{$!} #{name}"
	exit 1
end

