#!/usr/bin/ruby
$:.unshift File.join(File.dirname(__FILE__))
require 'AWS/IAM'
require 'basic_configuration'
require 'aws_context'
require 'pp'

if ARGV[0] == '-?' || ARGV.size < 3 then
    puts "usage: upload-signing-cert user-name -f certificate-file"
    exit 1
end
options = {}
options[:user_name] = ARGV[0]
cert_file = ARGV[2]

unless File.exist?(cert_file)
    puts "error: certificate file '#{cert_file}' doesn't exist"
    exit 1
end

Signal.trap("INT") do
    exit 2
end

options[:certificate_body] = ''
File.open(cert_file, "r") { |f|
    options[:certificate_body] = f.read
}

config = BasicConfiguration.new
iam = AwsContext.instance.iam(*config.keys)

begin
    result = iam.create_signing_certificate(options)
    puts "#{result.user_name} #{result.certificate_id} #{result.status}"
rescue
    puts "error uploading signing certificate: #{$!}"
    exit 1
end

exit 0